image: Visual Studio 2017

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: Visavi.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%nunit37%\nunit3-console.exe" -targetargs:".\VisaviTest\bin\Debug\VisaviTest.dll -noshadow" -filter:"+[Visavi*]* -[VisaviTest*]*" -output:".\visavi_coverage.xml"
- codecov -f "visavi_coverage.xml"
